### ISSUE TITLE
@cloud-ui/u-log-viewer.vue 这个组件可以单独使用吗

### ISSUE THREAD

**Issue by yaakua** [vusion/cloud-ui-materials#1]
我单独install 这个组件，并且import进来后，编译无法通过
![image](https://user-images.githubusercontent.com/1543846/77853054-7d943a00-7214-11ea-9b97-d658d15dba93.png)

错误信息如下：
![image](https://user-images.githubusercontent.com/1543846/77853062-8edd4680-7214-11ea-908b-c8f69435a95a.png)

**Comment by rainfore** [comment]
Hi，你好，我们这个系列的组件是 vusion 体系的，需要引入一些配置。

请问你是哪个公司？我们尝试出一个通用方案，解决你的问题。

**Comment by yaakua** [comment]
我是个人开发，需要在一个软件里面集成一个日志查看组件，刚好搜索到你们这个。尝试集成了一下，发现无法集成。

**Comment by rainfore** [comment]
### 1. 安装两个必要的 loader
``` shell
npm i --save-dev vusion-loader icon-font-loader
```

### 2. 添加配置 vue.config.js
``` js
```

**Comment by rainfore** [comment]
有什么问题可以继续沟通~

**Comment by lq782655835** [comment]
按需引入，除了webpack需要完全跟随vusion体系配置（即配置两个loader），还需要引入css变量

``` js
import 'cloud-ui.vusion/src/styles/theme.css' // css变量引入
```

详细可看vusion 按需引入示例项目：https://github.com/lq782655835/vusion-app-example

**Comment by xkkker** [comment]
按需引入时，报错如图，请问可以帮忙看下是什么错误吗？谢谢！

我想要使用的是ULogViewer这个组件，但是看起来它找不到base.css？

![image](https://user-images.githubusercontent.com/56376512/127970588-bb0b1e55-0ff2-4c76-ad20-6a967aaaa67b.png)
